@startuml
    ' association end properties are given in "{ }" brackets

    ' the "params" association end is ordered (i.e. preserving order, e.g. with a list)
    Method "1" *--> "0..*\nparams\n{ordered}" Parameter

    ' the "entries" association end is sorted
    TreeSet --> "*\nentries\n{sorted}" Entry

footer Rendered with PlantUML version %version()
@enduml