@startuml
	interface       List
	abstract        AbstractList
	abstract class  AbstractStack
	class           ConcreteClass
	entity          SomeEntity
	enum            DayOfWeek
	annotation      Nullable
	struct          SomeStruct
    exception       CustomException
    metaclass       SomeMetaClass

footer Rendered with PlantUML version %version()
@enduml