@startuml
    
    ' In newer PlantUML versions we can use a UML-compliant syntax.
    ' Adding '-' characters to the association definition increases its length.
    
    Shop [customerId: long] --> "customers\n1" Customer
    Customer [invoceNo: String] ---> "invoices\n1" Invoice

footer Rendered with PlantUML version %version()
@enduml