@startuml
    ' Our custom styling definitions
    <style>
        root {
            ' Use <<threadsafe>> for classes which are implemented thread safe.
            .threadsafe {
                FontColor DarkRed
                LineThickness 2
                LineColor DarkRed
            }
        
            ' Use <<external>> for elements outside the documented architectural element
            .external {
                ' <<focus>> also uses BackGroundColor.
                ' We assume that using <<focus>> and <<external>> on the same element
                ' makes no sense because external elements are by definition outside "focus". 
                BackGroundColor LightBlue
            }
        
            ' Use <<focus>> for the "rectangle" or "frame" which is subject of the containing document.
            ' E.g., if the .puml shows entities and sub-modules of a module.md, use
            ' "rectangle ThisModule <<Module>> <<focus>>"
            ' for the rectangle representing the module which is subject of this diagram.
            .focus {
                ' <<external>> also uses BackGroundColor.
                ' We assume that using <<focus>> and <<external>> on the same element
                ' makes no sense because external elements are by definition outside "focus". 
                BackGroundColor LightGray
            }
        }
    </style>
    
    hide <<focus>> stereotype

    together { 
        interface ExternalInterfaceUnsafe <<external>>
        class ExternalClassSafe <<external>> <<thread-safe>>
    }

    rectangle "System in focus" <<focus>> {
        class InternalClass
        class InternalClassFocus <<focus>>        
        class InternalClassSafe <<thread-safe>>
        class InternalClassSingleton <<Singleton>>
        ' You can highlight Singletons with a colored S icon if you like
        class InternalClassSingleton2 << (S,#FF7700) Singleton>>
        abstract class InternalAbstractClass
        interface InternalInterface
    }

    ExternalInterfaceUnsafe -[hidden]d- ExternalClassSafe
    InternalClassSingleton -[hidden]d- InternalClassSingleton2
    InternalInterface -[hidden]d- InternalAbstractClass
    InternalClass -[hidden]d- InternalClassFocus
    InternalClassFocus -[hidden]d- InternalClassSafe

    footer Rendered with PlantUML version %version()
@enduml