@startuml
    class A 
    class B <<special>>
    interface C
    class D

    D <|-- B

    ' hide all, but types with stereotype <<special>>
    hide *
    show <<special>>
    
    footer Rendered with PlantUML version %version()
@enduml