@startuml
    class A 
    class B <<special>>
    interface C
    class D

    D <|-- B

    ' remove all nodes with no edges
    remove @unlinked
    
    footer Rendered with PlantUML version %version()
@enduml