@startuml
    title Both smaller
    skinparam nodesep 15
    skinparam ranksep 25
    class Y
    interface Z
    A -> B
    A --> C
    A --> D
    A --> E
    E --> F
    E--> G
    X <|-- A

    footer Rendered with PlantUML version %version()    
@enduml