@startuml
    title Polyline routing
    skinparam linetype polyline
    
    A --> B
    A --> C
    A --> D
    X <|-- A
    Y <|.. A
    A --> E
    E --> Y

    footer Rendered with PlantUML version %version()
@enduml