@startuml
    title Left to right orientation
    left to right direction
    
    class A
    class B
    class C
    interface D
    interface E

    D <|-- A
    E <|-- B
    B -> A
    B *-- C

    footer Rendered with PlantUML version %version()
@enduml