@startuml
    ' with node groups and hidden edges:
    class D

    ' "together" defines a group of classes
    together {
        class A
        class E
        class F
    }
    A --> B
    A -> C
    C --> D

    ' a hidden edge from E to A forces position of class A
    E -[hidden]-> A
    
    footer Rendered with PlantUML version %version()
@enduml