@startuml
    title Orthogonal routing 
    skinparam linetype ortho
    
    A --> B
    A --> C
    A --> D
    X <|-- A
    Y <|.. A
    A --> E
    E --> Y

    footer Rendered with PlantUML version %version()
@enduml