@startuml
    ' use <u> ... </u> to underline the object name / type
    object "<u>linda : Person</u>" as linda {
        id: long = 18625
        firstName : String = "Linda"
        lastName: String = "Smith"
        gender : Gender = FEMALE
    }
    object "<u>c : Customer</u>" as c {
        id: long = 37829
        customerId : long = 1001
         
    }
    object "<u>: Company</u>" as e {
        id: long = 573
        name : String = "Great Enterprise" 
    } 
    linda -> "role" c
    c "customers" <--* e 

footer Rendered with PlantUML version %version()
@enduml