@startuml
    'The following line flattens the hierarchies
    set separator none

    package com.advantest.smartest.x.y.z {
        SomeClass -> OtherClass : thing
    }

footer Rendered with PlantUML version %version()
@enduml