@startuml
    'set separator none
    '!pragma useIntermediatePackages false 
    

    frame XYZ.SystemX.SystemY.SystemZ.SomeEntity {
	    package org.plantuml.test.system.impl {
	        class SomeClass {
	            doSomething(thing : Some.Certain.Type, other: Optional<String>)
            }
        }
    }

    footer Rendered with PlantUML version %version()

@enduml