@startuml
    'The following line flattens the hierarchies
    set separator none

    package org.test.module.x.y.z {
        SomeClass -> OtherClass : thing
    }

footer Rendered with PlantUML version %version()
@enduml