@startuml
    ' hide footer
    hide footbox

    ' external parts are highlighted in light blue,
    ' thread-safe implementations are highlighted in orange
    ' use "<u> ... </u>" as ... to underline the object name / type and naming the participant,
    ' if you want to be fully UML-compliant
    participant "<u>Client</u>" as Client #lightBlue
    participant "<u>ThreadPool</u>" as ThreadPool #orange
    participant "<u>t1: Thread</u>" as t1 #orange
    participant "<u>t2: Thread</u>" as t2 #orange

    activate Client
    activate ThreadPool
    activate t1
    
	Client -> ThreadPool : run(job1)
	' conditional messages are grouped in opt (optional) fragments (boxes) 
	opt threads not initialized
	   ThreadPool -> ThreadPool : init()
	end

    ' alternatives are grouped by alt fragments (boxes)
	alt idle thread available
	   ThreadPool -> ThreadPool ++ : findIdleThread()
	   ThreadPool --> ThreadPool -- : t1
	else no idle threads
       create t2
       ThreadPool -> t2 ++ : new
       ThreadPool --> ThreadPool -- : t2
	end

    ThreadPool --> Client : thread
	    
footer Rendered with PlantUML version %version()
@enduml