@startuml
    ' hide footer
    hide footbox

    ' messages can be automatically numbered,
    ' but beware, the numbers may change if you change the diagram
    autonumber

    participant Client

    ' use boxes to group relevant parts
    box important part
	    participant Service
	    participant OtherService
    end box

    activate Client
    Client -> Service ++ : request()
    Service -> Service ++ : calculate()
    Service -> OtherService ++ : otherRequest()
    OtherService --> Service -- : response
    Service --> Client -- : result
        
footer Rendered with PlantUML version %version()
@enduml