@startuml
    ' hide footer
    hide footbox

    actor User #lightBlue
    boundary Facade
    participant Controller
    participant Service

    ' activate lifeline with "activate" or "++"
    ' de-activate with "deactivate" or "--"
    activate User
    User -> Facade ++ : Request
    Facade -> Controller ++ : Request
    Controller -> Service ++ : handleRequest()
    create Response
    Service -> Response : new
    Service --> Controller -- : Response
    Controller --> Facade : Response
    deactivate Controller
    Facade --> User --

footer Rendered with PlantUML version %version()
@enduml