@startuml

    header PlantUML vers. %version()
    
    class TestClass
    interface X
    
    TestClass ..|> X
    
    left footer ENV VAR "PLANTUML_SECURITY_PROFILE": %getenv("PLANTUML_SECURITY_PROFILE")\nENV VAR "PATH": %getenv("PATH")\nENV VAR "WORKSPACE": %getenv("WORKSPACE")\nfile: %filename()\ncurrent path: %dirpath()

@enduml