source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               resources/,\
               plugin.xml,\
               schema/,\
               lib/antlr-runtime-3.5.2.jar,\
               lib/antlr4-runtime-4.7.1.jar,\
               lib/ST4-4.0.8.jar,\
               lib/txtmark-0.13.jar,\
               lib/annotations-24.0.1.jar,\
               lib/autolink-0.6.0.jar,\
               lib/flexmark-0.65.2-20260519-1651.jar,\
               lib/markdown-core-1.0.11-20260521-1035.jar,\
               lib/flexmark-util-visitor-0.65.2-20260519-1651.jar,\
               lib/flexmark-util-sequence-0.65.2-20260519-1651.jar,\
               lib/flexmark-util-options-0.65.2-20260519-1651.jar,\
               lib/flexmark-util-misc-0.65.2-20260519-1651.jar,\
               lib/flexmark-util-html-0.65.2-20260519-1651.jar,\
               lib/flexmark-util-format-0.65.2-20260519-1651.jar,\
               lib/flexmark-util-dependency-0.65.2-20260519-1651.jar,\
               lib/flexmark-util-data-0.65.2-20260519-1651.jar,\
               lib/flexmark-util-collection-0.65.2-20260519-1651.jar,\
               lib/flexmark-util-builder-0.65.2-20260519-1651.jar,\
               lib/flexmark-util-ast-0.65.2-20260519-1651.jar,\
               lib/flexmark-util-0.65.2-20260519-1651.jar,\
               lib/flexmark-ext-tables-0.65.2-20260519-1651.jar,\
               lib/flexmark-ext-jira-ticket-links-1.0.0-20260521-0957.jar,\
               lib/flexmark-ext-plantuml-1.0.0-20260521-0957.jar,\
               lib/flexmark-ext-math-1.0.0-20260521-0957.jar,\
               lib/flexmark-ext-gfm-strikethrough-0.65.2-20260519-1651.jar,\
               lib/flexmark-ext-footnotes-0.65.2-20260519-1651.jar,\
               lib/flexmark-ext-figures-1.0.0-20260521-0957.jar,\
               lib/flexmark-ext-autolink-0.65.2-20260519-1651.jar,\
               lib/flexmark-ext-attributes-0.65.2-20260519-1651.jar
src.includes = resources/,\
               pom.xml,\
               .settings/
jre.compilation.profile = JavaSE-21
